export interface ISchoolDetails {
  id: number;
  imageAttachmentId: number;
  name: string;
  regionName: string;
  districtName: string;
  address: string;
  socialNetwork: string;
  webPage: string;
  principal: string;
  educationStatus: string;
  schoolType: string;
  buildingCount: number;
  authorizationStartDate: string;
  authorizationEndDate: string;
  email: string;
  phoneNumber: string;
  studentCount: number;
  teacherCount: number;
  sectors: string;
  mission: boolean;
  structure: boolean;
  programsandsupport: boolean;
  behaviorrulesandappellation: boolean;
  infrastructure: boolean;
  finance: boolean;
  strategicplan: boolean;
  yearlyactionplan: boolean;
}
